import AppKit
import PanesCore
import os

/// `changeCount` polling — still the only way to observe the pasteboard on
/// macOS; there is no public change notification. 0.3 s keeps copies feeling
/// instant at negligible cost (the no-change path is one integer compare).
///
/// Privacy rules a history tool must respect:
///  - Skip anything marked with the nspasteboard.org convention types
///    (transient/concealed/auto-generated) — that's how password managers
///    say "do not record me".
///  - macOS 15.4+ Pasteboard Privacy: programmatic READS of content can
///    surface a user alert depending on the per-app "Paste from Other Apps"
///    setting. changeCount and type sniffing are free; content reads are the
///    gated operation. A clipboard manager needs the user to set Panes to
///    "Always Allow" — surface that during onboarding.
final class PasteboardWatcher: NSObject {
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        // Our own paste-backs (set by PasteService) — recording them would
        // duplicate history entries.
        PasteService.pasteBackMarker,
    ]
    /// Cap on the STORED (re-encoded PNG) size — generous enough for
    /// full-screen retina screenshots, which is the main thing users expect to
    /// find in history.
    private static let maxImageBytes = 24 * 1024 * 1024

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    // Per-kind dedup so re-copying the same thing doesn't add a duplicate, and
    // so a file list never suppresses a later identical-looking text copy.
    private var lastText: String?
    private var lastFiles: String?
    private var lastImageHash: Int?
    private let onCapture: (ClipboardItem.Kind, String?, Data?, String?) -> Void
    /// Bundle IDs the user excluded; read live each time content changes so the
    /// list takes effect without restarting the watcher.
    private let excludedBundleIDs: () -> Set<String>
    private let log = Logger.panes("clipboard-watch")

    init(
        excludedBundleIDs: @escaping () -> Set<String> = { [] },
        onCapture: @escaping (ClipboardItem.Kind, String?, Data?, String?) -> Void
    ) {
        self.excludedBundleIDs = excludedBundleIDs
        self.onCapture = onCapture
        super.init()
    }

    func start() {
        guard timer == nil else { return }
        // Target/selector (not the block API) so the @objc main-thread fire
        // path needs no Sendable contortions.
        let timer = Timer(
            timeInterval: 0.3,
            target: self,
            selector: #selector(poll),
            userInfo: nil,
            repeats: true
        )
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    @objc private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // macOS 15.4+ Pasteboard Privacy: content reads are the gated
        // operation (changeCount/types are always free). Respect an explicit
        // deny; under .ask each read can surface a system alert, so
        // onboarding should walk the user to "Always Allow".
        if #available(macOS 15.4, *) {
            switch pasteboard.accessBehavior {
            case .alwaysDeny:
                return
            case .ask:
                // Reading content under "Ask" alerts on EVERY copy (we poll
                // continuously). Skip capture until the user sets Panes to
                // Always Allow, rather than spamming the system prompt.
                log.notice("pasteboard access is 'Ask' — skipping capture until set to Always Allow")
                return
            default:
                break
            }
        }

        // Scan every item's types (not just the first) so a paste-back marker
        // or a privacy tag on any item is honored. Reading types is metadata,
        // not gated content.
        let types = Set(pasteboard.pasteboardItems?.flatMap { $0.types } ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        // Skip copies made from an excluded app before reading any content.
        if let source, excludedBundleIDs().contains(source) { return }

        // File lists beat plain text (Finder copies write both).
        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           !urls.isEmpty {
            let joined = urls.map(\.path).joined(separator: "\n")
            guard joined != lastFiles else { return }
            lastFiles = joined
            onCapture(.fileList, joined, nil, source)
            return
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            guard text != lastText else { return }
            lastText = text
            onCapture(.text, text, nil, source)
            return
        }

        if types.contains(.png) || types.contains(.tiff) {
            guard let raw = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) else { return }
            // Store a compressed PNG. A clipboard screenshot is often a huge
            // TIFF; re-encoding shrinks it a lot so it fits and doesn't bloat
            // the history database.
            let png = NSBitmapImageRep(data: raw)?.representation(using: .png, properties: [:]) ?? raw
            guard png.hashValue != lastImageHash else { return }
            if png.count <= Self.maxImageBytes {
                lastImageHash = png.hashValue
                onCapture(.image, nil, png, source)
            } else {
                log.debug("skipping oversized image (\(png.count) bytes)")
            }
        }
    }
}
